language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi

install:
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then travis_retry composer install --no-interaction --prefer-source; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.2" ]; then phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then vendor/bin/phpunit; fi
